### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by luckydevil13** [tntmod54321/7z-deglover#1]
```
Traceback (most recent call last):
  File "C:\Users\l\Downloads\11111111111111111111111\7z_deglover.py", line 112, in buildLZMA2Index
    IS_LAST_PACKET = blockEnd-packetEnd<=2
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

During handling of the above exception, another exception occurred:
```

data from -P option is

```
Verifying file type...
Building LZMA2 index...

0x20			packet 1:
packet type:			COMPRESSED_LZMA2, DICT_RESET
LZMA2 packet header:		E2 9D 20 C0 04 5D 
uncompressed packet bytecount:	171297 bytes
compressed packet bytecount:	49157 bytes
packet state control flags:	3 (0b11100010)
property state;			0x5d
end of current packet is 0x23
start of next packet is 0x2
0xc02a

0xc02b			packet 2:
packet type:			UNCOMPRESSED_LZMA2
LZMA2 packet header:		02 BE 63 
uncompressed packet bytecount:	48740 bytes
compressed packet bytecount:	N/A
packet state control flags:	N/A
property state;			N/A
end of current packet is 0xce
start of next packet is 0x2
0x17e91



......
skip
......

0xf02df2a1			packet 82906:
packet type:			UNCOMPRESSED_LZMA2
LZMA2 packet header:		02 BD 86 
uncompressed packet bytecount:	48519 bytes
compressed packet bytecount:	N/A
packet state control flags:	N/A
property state;			N/A
end of current packet is 0xae
start of next packet is 0x2
0xf02eb02a

0xf02eb02b			packet 82907:
packet type:			UNCOMPRESSED_LZMA2
LZMA2 packet header:		02 86 66 
uncompressed packet bytecount:	34407 bytes
compressed packet bytecount:	N/A
packet state control flags:	N/A
property state;			N/A
end of current packet is 0x0
start of next packet is 0x0
0xf02f3694

0xf02f3695			packet 82908:

```

try to skips 0xf02f3695 but got the same error

**Comment by tntmod54321** [comment]
`packetEnd` is set to `None` because the control-byte for the packet it tries to read is `0x00`, it's likely that the start of where a packet should be is null or invalid data, what's the following exception? there's code to handle the TypeError exception.

**Comment by luckydevil13** [comment]
@tntmod54321 could we do something with it? it's important archive to me. Could we skip such block ?

**Comment by tntmod54321** [comment]
Yeah it should be possible, but it's crashing for some reason, what is the exception that occurs after the TypeError? Maybe if it's not too personal you could send me the file, my discord is in my bio.

**Comment by luckydevil13** [comment]
@tntmod54321 full log looks like this

```
c:\Users\UC254004\Downloads>python 7z_deglover.py -i Downloads.7z -o qq
Verifying file type...
Building LZMA2 index...
Traceback (most recent call last):
  File "c:\Users\UC254004\Downloads\7z_deglover.py", line 112, in buildLZMA2Index
    IS_LAST_PACKET = blockEnd-packetEnd<=2
                     ~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\UC254004\Downloads\7z_deglover.py", line 369, in <module>
    main()
  File "c:\Users\UC254004\Downloads\7z_deglover.py", line 233, in main
    packets, x = buildLZMA2Index(arcbuf, footerOffset, doPrintout=printPackets, breakAfterX=0, skips=skips)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\UC254004\Downloads\7z_deglover.py", line 118, in buildLZMA2Index
    raise Exception(f'Error reading lzma2 packet header at {hex(packetOffset)}, try specifying a skip? Use -P to printout packet debug info')
Exception: Error reading lzma2 packet header at 0xf02f3695, try specifying a skip? Use -P to printout packet debug info

c:\Users\UC254004\Downloads>python 7z_deglover.py -i Downloads.7z -o qq --skips 0xf02f3695
Verifying file type...
Building LZMA2 index...
using skip 0 to skip from 0xf02f3695 to 0xf02f3695
Traceback (most recent call last):
  File "c:\Users\UC254004\Downloads\7z_deglover.py", line 112, in buildLZMA2Index
    IS_LAST_PACKET = blockEnd-packetEnd<=2
                     ~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\UC254004\Downloads\7z_deglover.py", line 369, in <module>
    main()
  File "c:\Users\UC254004\Downloads\7z_deglover.py", line 233, in main
    packets, x = buildLZMA2Index(arcbuf, footerOffset, doPrintout=printPackets, breakAfterX=0, skips=skips)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\UC254004\Downloads\7z_deglover.py", line 118, in buildLZMA2Index
    raise Exception(f'Error reading lzma2 packet header at {hex(packetOffset)}, try specifying a skip? Use -P to printout packet debug info')
Exception: Error reading lzma2 packet header at 0xf02f3695, try specifying a skip? Use -P to printout packet debug info
```


archive is huge: 17Gb.

Could we setup meet via google hangout?

**Comment by tntmod54321** [comment]
Ah ok I see, you're using --skips wrong, you're not supposed to tell it to skip that packet, you're supposed to tell it when the next valid packet begins (it has no way of knowing for sure), you have to manually find the next valid address using a hex editor, this could in theory be done automatically but it was a lot of work and could theoretically get invalid data so I never implemented it.  
I won't be able to join a voice call but we can text there if you want, I'd have to have a copy of the file to be able to tell you where to skip to, it's entirely possible that there are multiple damaged portions, aswell.

**Comment by luckydevil13** [comment]
@tntmod54321 could you please add some comments regarding possible address to skip according to last 3 items logs? how to calculate?
I see 48519 uncompressed packet bytecount +-, and last packet it smaller
```
0xf02c7751			packet 82904:
packet type:			UNCOMPRESSED_LZMA2
LZMA2 packet header:		02 BD 94 
uncompressed packet bytecount:	48533 bytes
compressed packet bytecount:	N/A
packet state control flags:	N/A
property state;			N/A
end of current packet is 0xa3
start of next packet is 0x2
0xf02d34e8

0xf02d34e9			packet 82905:
packet type:			UNCOMPRESSED_LZMA2
LZMA2 packet header:		02 BD B4 
uncompressed packet bytecount:	48565 bytes
compressed packet bytecount:	N/A
packet state control flags:	N/A
property state;			N/A
end of current packet is 0xf2
start of next packet is 0x2
0xf02df2a0

0xf02df2a1			packet 82906:
packet type:			UNCOMPRESSED_LZMA2
LZMA2 packet header:		02 BD 86 
uncompressed packet bytecount:	48519 bytes
compressed packet bytecount:	N/A
packet state control flags:	N/A
property state;			N/A
end of current packet is 0xae
start of next packet is 0x2
0xf02eb02a

0xf02eb02b			packet 82907:
packet type:			UNCOMPRESSED_LZMA2
LZMA2 packet header:		02 86 66 
uncompressed packet bytecount:	34407 bytes
compressed packet bytecount:	N/A
packet state control flags:	N/A
property state;			N/A
end of current packet is 0x0
start of next packet is 0x0
0xf02f3694

0xf02f3695			packet 82908:

```

**Comment by tntmod54321** [comment]
It isn't possible to figure out where to skip to just from the packet printouts, `packet 82908` is null/corrupted, you need to use a hex editor to figure out where the next valid packet is.  
You also can't really guess it, you have to specify the exact starting byte.

**Comment by luckydevil13** [comment]
Can I use LZMA2 packet header:		02 86 YY as start point?

**Comment by tntmod54321** [comment]
Yes that could be valid, if it is then the program should either run until completion or will run for a short bit of time before encountering more bad data, if it doesn't get much further then it's probably not valid.

**Comment by luckydevil13** [comment]
Ok, lets imagine next valid packet is

```
0xf02ebABC			packet 82908:
packet type:			UNCOMPRESSED_LZMA2
LZMA2 packet header:		02 86 66 
```

how to specify --skip param correct to it? --skip 0xf02ebABC ?

**Comment by tntmod54321** [comment]
That would be how you correctly skip (--skip**s** instead), BUT, the program won't print where you need to skip to, so if it's printing that message then that packet is not the next valid packet.

**Comment by luckydevil13** [comment]
@tntmod54321 just tried on 7z-deglover on correct 7z and got error:


```
 File "C:\Users\UC254004\Downloads\7z_deglover.py", line 369, in <module>
    main()
  File "C:\Users\UC254004\Downloads\7z_deglover.py", line 233, in main
    packets, x = buildLZMA2Index(arcbuf, footerOffset, doPrintout=printPackets, breakAfterX=0, skips=skips)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\UC254004\Downloads\7z_deglover.py", line 118, in buildLZMA2Index
    raise Exception(f'Error reading lzma2 packet header at {hex(packetOffset)}, try specifying a skip? Use -P to printout packet debug info')
Exception: Error reading lzma2 packet header at 0x59821d, try specifying a skip? Use -P to printout packet debug info

```
